version: '3'
services:
  redis:
    image: redis:4.0.6-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  api:
    image: thumbnailed:latest
    command: uvicorn api:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    depends_on:
      - redis
    links:
      - redis
  worker:
    image: thumbnailed:latest
    command: rq worker --url redis://redis:6379 thumbrequests
    depends_on:
      - redis
    links:
      - redis

  dashboard:
    image: eoranged/rq-dashboard
    ports:
      - 9181:9181
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    links:
      - redis